### ISSUE TITLE
Any plans for supporting distributed runners?

### ISSUE THREAD

**Issue by rcowham** [form3tech-oss/f1#116]
Currently using locust which has options for distributed runners (non-web testing).

Do you have any plans to do such things with f1?

**Comment by andykuszyk-form3** [comment]
Hi @rcowham :wave: 

Sorry for the delay in responding.

What do you mean by distributed runners? Do you mean F1 orchestrating load test executions across multiple processes?

If so, we don't currently have any plans to implement this sort of thing. Internally, we normally orchestrate large and varied load tests by running several separate instances of F1.
