### ISSUE TITLE
wrong Twitter handle @F3FinCloud used on the Form3 main GitHub page

### ISSUE THREAD

**Issue by nikitakoselev** [form3tech-oss/f1#120]
Problem:
This is not an F1 issue, but the https://github.com/form3tech-oss issue.  
"Twitter" hyperlink in "Thanks for stopping by! partying_face" at "https://github.com/form3tech-oss" is referring to the @F3FinCloud account, which does not exist any longer.

![Screenshot_20230109_183423](https://user-images.githubusercontent.com/6383738/211384408-951fceb8-23b2-47e1-b428-a503f013634a.png)
![Screenshot_20230109_183454](https://user-images.githubusercontent.com/6383738/211384412-8a532b7a-435f-47a3-8a48-81ecd63b73a7.png)
![Screenshot_20230109_183454](https://user-images.githubusercontent.com/6383738/211385027-6ffefb93-0c11-4b03-8747-dcfa239169a5.png)

Solution:
Please update the Twitter handle to one of the active ones, for example: @Form3Tech or form3careers

**Comment by nvloff-f3** [comment]
Thank you!

Twitter mention removed: https://github.com/form3tech-oss/.github/pull/10
