### ISSUE TITLE
How can we pass unique data to each iteration?

### ISSUE THREAD

**Issue by suhaibm7** [form3tech-oss/f1#130]
I have a data set which should be consumed by each iteration, however I want to pass a single record to single iteration, thus passing n records to n different iterations

**Comment by andykuszyk-form3** [comment]
Hi @suhaibm7 :wave: 

There's no built-in support for that, I think you would need to implement that in your test scenarios.

F1 is limited more to the runner which injects load into your specific test scenarios.

Thanks for the question :slightly_smiling_face:
